const clothes = [
  /***************** Hoodies *************************** */
  {
    id: 1,
    name: "White Classic Hoodie",
    category: "Hoodies",
    price: 650,
    sizes: ["S", "M", "L", "XL"],
    color: "White",
    inStock: true,
    rating: 4.5,
    image: "./img/a18fa2101e8a191ecc1023de3701dac2.jpg",
  },
  {
    id: 2,
    name: "Gray Everyday Hoodie",
    category: "Hoodies",
    price: 670,
    sizes: ["S", "M", "L"],
    color: "Gray",
    inStock: true,
    rating: 4.3,
    image: "./img/2b2355147034be29a4c2237bcb6eca5a.jpg",
  },
  {
    id: 3,
    name: "Navy Pullover Hoodie",
    category: "Hoodies",
    price: 690,
    sizes: ["S", "M", "L", "XL"],
    color: "Navy",
    inStock: true,
    rating: 4.1,
    image: "./img/4a55763c24f98ad6d1f8c97423cf632b.jpg",
  },
  {
    id: 4,
    name: "Olive Zip Sweatshirt",
    category: "Hoodies",
    price: 690,
    sizes: ["S", "M", "L"],
    color: "Olive Green",
    inStock: true,
    rating: 3.9,
    image: "./img/6ed3bfc99ebc4c1fdd0a65a4cd44cd29.jpg",
  },
  {
    id: 5,
    name: "Blue Full Zip Hoodie",
    category: "Hoodies",
    price: 710,
    sizes: ["S", "M", "L", "XL"],
    color: "Blue",
    inStock: true,
    rating: 5.0,
    image: "./img/7d6d6a89003e4776b8d6ce3e35d06574.jpg",
  },
  {
    id: 6,
    name: "Beige Zip Sweatshirt",
    category: "Hoodies",
    price: 730,
    sizes: ["S", "M", "L"],
    color: "Beige",
    inStock: false,
    rating: 4.8,
    image: "./img/20aee50b38ee995541b59f977193d2b5.jpg",
  },
  {
    id: 7,
    name: "Red Cropped Pullover",
    category: "Hoodies",
    price: 730,
    sizes: ["S", "M", "L", "XL"],
    color: "Red",
    inStock: true,
    rating: 4.6,
    image: "./img/419e5e17b77c776e02a1696ad8501534.jpg",
  },
  {
    id: 8,
    name: "Black Cropped Hoodie",
    category: "Hoodies",
    price: 750,
    sizes: ["S", "M", "L"],
    color: "Black",
    inStock: true,
    rating: 4.4,
    image: "./img/b36e6c00c6d8c5a3ab167c4266808450.jpg",
  },
  {
    id: 9,
    name: "White Cropped Hoodie",
    category: "Hoodies",
    price: 770,
    sizes: ["S", "M", "L", "XL"],
    color: "White",
    inStock: true,
    rating: 4.2,
    image: "./img/bca1f94fde8fbb4eebd95ab2475be07a.jpg",
  },
  {
    id: 10,
    name: "Gray Heavyweight Top",
    category: "Hoodies",
    price: 770,
    sizes: ["S", "M", "L"],
    color: "Gray",
    inStock: true,
    rating: 4.0,
    image: "./img/5d6325a0dcac12dc8b20e1187a904a69.jpg",
  },
  {
    id: 11,
    name: "Navy Heavyweight Top",
    category: "Hoodies",
    price: 790,
    sizes: ["S", "M", "L", "XL"],
    color: "Navy",
    inStock: true,
    rating: 3.8,
    image: "./img/412b35518f56737656bdf5065b86b46f.jpg",
  },
  {
    id: 12,
    name: "Olive Heavy Pullover",
    category: "Hoodies",
    price: 810,
    sizes: ["S", "M", "L"],
    color: "Olive Green",
    inStock: true,
    rating: 4.9,
    image: "./img/355703bd3c157229bf9982190e6b088d.jpg",
  },
  {
    id: 13,
    name: "Blue Fleece Pullover",
    category: "Hoodies",
    price: 810,
    sizes: ["S", "M", "L", "XL"],
    color: "Blue",
    inStock: false,
    rating: 4.7,
    image: "./img/d14648d6c5ec0892cc98cdba19f7b4d8.jpg",
  },
  {
    id: 14,
    name: "Beige Fleece Sweater",
    category: "Hoodies",
    price: 830,
    sizes: ["S", "M", "L"],
    color: "Beige",
    inStock: true,
    rating: 4.5,
    image: "./img/0764f1c0fd5232c0a0c9ea35332c1286.jpg",
  },
  {
    id: 15,
    name: "Red Thick Fleece Top",
    category: "Hoodies",
    price: 850,
    sizes: ["S", "M", "L", "XL"],
    color: "Red",
    inStock: true,
    rating: 4.3,
    image: "./img/a0a0371d2ab39480aeec7e6710f883ed.jpg",
  },

  /***************** T-Shirts *************************** */
  {
    id: 16,
    name: "Black Oversize Shirt",
    category: "T-Shirts",
    price: 250,
    sizes: ["S", "M", "L"],
    color: "Black",
    inStock: true,
    rating: 4.9,
    image: "img/cfa5d3d733f73c5d86f0eaf46f25a637.jpg",
  },
  {
    id: 17,
    name: "White Oversize Shirt",
    category: "T-Shirts",
    price: 270,
    sizes: ["S", "M", "L", "XL"],
    color: "White",
    inStock: true,
    rating: 4.7,
    image: "./img/3937b7a8cca92b69cc81e46ac1e6af5b.jpg",
  },
  {
    id: 18,
    name: "Gray Oversized Shirt",
    category: "T-Shirts",
    price: 290,
    sizes: ["S", "M", "L"],
    color: "Gray",
    inStock: true,
    rating: 4.5,
    image: "./img/757b34ba70b466c3a3853a2c12c34585.jpg",
  },
  {
    id: 19,
    name: "Navy Graphic T-Shirt",
    category: "T-Shirts",
    price: 290,
    sizes: ["S", "M", "L", "XL"],
    color: "Navy",
    inStock: true,
    rating: 4.3,
    image: "./img/3a00c6aa1af694b2817c2989a3916138.jpg",
  },
  {
    id: 20,
    name: "Olive Logo Print Tee",
    category: "T-Shirts",
    price: 310,
    sizes: ["S", "M", "L"],
    color: "Olive Green",
    inStock: true,
    rating: 4.1,
    image: "./img/5bb877a123227601450cda8be4f4b4c9.jpg",
  },
  {
    id: 21,
    name: "Blue Art Graphic Tee",
    category: "T-Shirts",
    price: 330,
    sizes: ["S", "M", "L", "XL"],
    color: "Blue",
    inStock: true,
    rating: 3.9,
    image: "./img/6a2e5f9d8554e9029c84c5891f5776ef.jpg",
  },
  {
    id: 22,
    name: "Beige Boxy Fit Shirt",
    category: "T-Shirts",
    price: 330,
    sizes: ["S", "M", "L"],
    color: "Beige",
    inStock: false,
    rating: 5.0,
    image: "./img/1ad6d71969875903afdf16c1a3f93707.jpg",
  },
  {
    id: 23,
    name: "Red Boxy Fit T-Shirt",
    category: "T-Shirts",
    price: 350,
    sizes: ["S", "M", "L", "XL"],
    color: "Red",
    inStock: true,
    rating: 4.8,
    image: "./img/db0b28634c0030faf55a9c3014ca09c4.jpg",
  },
  {
    id: 24,
    name: "Black Boxy Fit Shirt",
    category: "T-Shirts",
    price: 370,
    sizes: ["S", "M", "L"],
    color: "Black",
    inStock: true,
    rating: 4.6,
    image: "./img/d6387580f134da427e6bf391de7e1d33.jpg",
  },
  {
    id: 25,
    name: "White Pocket T-Shirt",
    category: "T-Shirts",
    price: 370,
    sizes: ["S", "M", "L", "XL"],
    color: "White",
    inStock: true,
    rating: 4.4,
    image: "./img/4ef035518a893ef26215dd08eccf665d.jpg",
  },
  {
    id: 26,
    name: "Gray Pocket Crew Tee",
    category: "T-Shirts",
    price: 390,
    sizes: ["S", "M", "L"],
    color: "Gray",
    inStock: true,
    rating: 4.2,
    image: "./img/6f6420d757c47c02ecc1c5f1248bd205.jpg",
  },
  {
    id: 27,
    name: "Navy Pocket Crew Tee",
    category: "T-Shirts",
    price: 410,
    sizes: ["S", "M", "L", "XL"],
    color: "Navy",
    inStock: true,
    rating: 4.0,
    image: "./img/9b8182b10097917fd8c09418fb3622c7.jpg",
  },
  {
    id: 28,
    name: "Olive Stripe T-Shirt",
    category: "T-Shirts",
    price: 410,
    sizes: ["S", "M", "L"],
    color: "Olive Green",
    inStock: true,
    rating: 3.8,
    image: "./img/69a4770ae2a884ce26566ad293348051.jpg",
  },
  {
    id: 29,
    name: "Blue Striped T-Shirt",
    category: "T-Shirts",
    price: 430,
    sizes: ["S", "M", "L", "XL"],
    color: "Blue",
    inStock: false,
    rating: 4.9,
    image: "./img/992c811d3c4229660f7c79d040d586c6.jpg",
  },
  {
    id: 30,
    name: "Beige Stripe T-Shirt",
    category: "T-Shirts",
    price: 450,
    sizes: ["S", "M", "L"],
    color: "Beige",
    inStock: true,
    rating: 4.7,
    image: "./img/58991e9ac63ea20ff8dfdd6e32b8b380.jpg",
  },

  /***************** Pants *************************** */
  {
    id: 31,
    name: "Gray Baggy Fit Jeans",
    category: "Pants",
    price: 750,
    sizes: ["30", "32", "34"],
    color: "Gray",
    inStock: true,
    rating: 4.1,
    image: "./img/ff1bf66ab9a55941dd3177d641dadf9c.jpg",
  },
  {
    id: 32,
    name: "Navy Baggy Fit Jeans",
    category: "Pants",
    price: 770,
    sizes: ["30", "32", "34", "36"],
    color: "Navy",
    inStock: true,
    rating: 3.9,
    image: "./img/f2596a34e39f269a9fda39b8b2db19b0.jpg",
  },
  {
    id: 33,
    name: "Olive Wide Leg Jeans",
    category: "Pants",
    price: 790,
    sizes: ["30", "32", "34"],
    color: "Olive Green",
    inStock: true,
    rating: 5.0,
    image: "./img/f933ee1bfed15a2fcabdb89ec96f96c4.jpg",
  },
  {
    id: 34,
    name: "Blue Tactical Cargos",
    category: "Pants",
    price: 790,
    sizes: ["30", "32", "34", "36"],
    color: "Blue",
    inStock: true,
    rating: 4.8,
    image: "./img/d6d84de723a20bf795efe249c1e3e4d7.jpg",
  },
  {
    id: 35,
    name: "Beige Utility Cargos",
    category: "Pants",
    price: 810,
    sizes: ["30", "32", "34"],
    color: "Beige",
    inStock: false,
    rating: 4.6,
    image: "./img/c54537325d7d11d4e90e26401ea9ad5a.jpg",
  },
  {
    id: 36,
    name: "Red Cargo Work Pants",
    category: "Pants",
    price: 830,
    sizes: ["30", "32", "34", "36"],
    color: "Red",
    inStock: true,
    rating: 4.4,
    image: "./img/bcb19d9ff75aa53fc74af95488839bff.jpg",
  },
  {
    id: 37,
    name: "Black Casual Joggers",
    category: "Pants",
    price: 830,
    sizes: ["30", "32", "34"],
    color: "Black",
    inStock: true,
    rating: 4.2,
    image: "./img/b2848a56392dbd39ee7cb63269941bbf.jpg",
  },
  {
    id: 38,
    name: "White Casual Joggers",
    category: "Pants",
    price: 850,
    sizes: ["30", "32", "34", "36"],
    color: "White",
    inStock: true,
    rating: 4.0,
    image: "./img/2ed8f36366edf8cb77f6a64df81f4981.jpg",
  },
  {
    id: 39,
    name: "Gray Comfort Joggers",
    category: "Pants",
    price: 870,
    sizes: ["30", "32", "34"],
    color: "Gray",
    inStock: true,
    rating: 3.8,
    image: "./img/80d3ca8163327b751520f52e3dab8ce5.jpg",
  },
  {
    id: 40,
    name: "Navy Wide-Leg Slacks",
    category: "Pants",
    price: 870,
    sizes: ["30", "32", "34", "36"],
    color: "Navy",
    inStock: true,
    rating: 4.9,
    image: "./img/301c95cf2898b7395731f8a640878de4.jpg",
  },
  {
    id: 41,
    name: "Olive Wide-Leg Pants",
    category: "Pants",
    price: 890,
    sizes: ["30", "32", "34"],
    color: "Olive Green",
    inStock: true,
    rating: 4.7,
    image: "./img/239f27369977889624a7dd3c1af989e1.jpg",
  },
  {
    id: 42,
    name: "Blue Wide-Leg Slacks",
    category: "Pants",
    price: 910,
    sizes: ["30", "32", "34", "36"],
    color: "Blue",
    inStock: false,
    rating: 4.5,
    image: "./img/4530af16ac42caa0fa7a07e2727fa328.jpg",
  },
  {
    id: 43,
    name: "Beige Straight Jeans",
    category: "Pants",
    price: 910,
    sizes: ["30", "32", "34"],
    color: "Beige",
    inStock: true,
    rating: 4.3,
    image: "./img/5871ef9bbca0c081afa35f7b2023b234.jpg",
  },
  {
    id: 44,
    name: "Red Daily Wear Jeans",
    category: "Pants",
    price: 930,
    sizes: ["30", "32", "34", "36"],
    color: "Red",
    inStock: true,
    rating: 4.1,
    image: "./img/38751d7a086aa96ec95fc2b3237defaa.jpg",
  },
  {
    id: 45,
    name: "Black Straight Jeans",
    category: "Pants",
    price: 950,
    sizes: ["30", "32", "34"],
    color: "Black",
    inStock: true,
    rating: 3.9,
    image: "./img/c54537325d7d11d4e90e26401ea9ad5a.jpg",
  },

  /***************** Jackets *************************** */
  {
    id: 46,
    name: "Navy Bomber Zip Coat",
    category: "Jackets",
    price: 1000,
    sizes: ["M", "L", "XL"],
    color: "Navy",
    inStock: true,
    rating: 5.0,
    image: "https://placehold.co/400x500/1f2a44/fff?text=Navy+Bomber+Jacket",
  },
  {
    id: 47,
    name: "Olive Classic Bomber",
    category: "Jackets",
    price: 1020,
    sizes: ["M", "L"],
    color: "Olive Green",
    inStock: true,
    rating: 4.8,
    image:
      "https://placehold.co/400x500/556b2f/fff?text=Olive+Green+Bomber+Jacket",
  },
  {
    id: 48,
    name: "Blue Bomber Zip Coat",
    category: "Jackets",
    price: 1040,
    sizes: ["M", "L", "XL"],
    color: "Blue",
    inStock: true,
    rating: 4.6,
    image: "https://placehold.co/400x500/2a4d8f/fff?text=Blue+Bomber+Jacket",
  },
  {
    id: 49,
    name: "Beige Trucker Jacket",
    category: "Jackets",
    price: 1040,
    sizes: ["M", "L"],
    color: "Beige",
    inStock: false,
    rating: 4.4,
    image: "https://placehold.co/400x500/d8c9a8/000?text=Beige+Denim+Jacket",
  },
  {
    id: 50,
    name: "Red Denim Jacket Fit",
    category: "Jackets",
    price: 1060,
    sizes: ["M", "L", "XL"],
    color: "Red",
    inStock: true,
    rating: 4.2,
    image: "https://placehold.co/400x500/b22222/fff?text=Red+Denim+Jacket",
  },
  {
    id: 51,
    name: "Black Trucker Jacket",
    category: "Jackets",
    price: 1080,
    sizes: ["M", "L"],
    color: "Black",
    inStock: true,
    rating: 4.0,
    image: "https://placehold.co/400x500/111/fff?text=Black+Denim+Jacket",
  },
  {
    id: 52,
    name: "White Varsity Jacket",
    category: "Jackets",
    price: 1080,
    sizes: ["M", "L", "XL"],
    color: "White",
    inStock: true,
    rating: 3.8,
    image: "https://placehold.co/400x500/eee/000?text=White+Varsity+Jacket",
  },
  {
    id: 53,
    name: "Gray Classic Varsity",
    category: "Jackets",
    price: 1100,
    sizes: ["M", "L"],
    color: "Gray",
    inStock: true,
    rating: 4.9,
    image: "https://placehold.co/400x500/888/fff?text=Gray+Varsity+Jacket",
  },
  {
    id: 54,
    name: "Navy Classic Varsity",
    category: "Jackets",
    price: 1120,
    sizes: ["M", "L", "XL"],
    color: "Navy",
    inStock: true,
    rating: 4.7,
    image: "https://placehold.co/400x500/1f2a44/fff?text=Navy+Varsity+Jacket",
  },
  {
    id: 55,
    name: "Olive Outdoor Jacket",
    category: "Jackets",
    price: 1120,
    sizes: ["M", "L"],
    color: "Olive Green",
    inStock: true,
    rating: 4.5,
    image:
      "https://placehold.co/400x500/556b2f/fff?text=Olive+Green+Windbreaker",
  },
  {
    id: 56,
    name: "Blue Zip Windbreaker",
    category: "Jackets",
    price: 1140,
    sizes: ["M", "L", "XL"],
    color: "Blue",
    inStock: false,
    rating: 4.3,
    image: "https://placehold.co/400x500/2a4d8f/fff?text=Blue+Windbreaker",
  },
  {
    id: 57,
    name: "Beige Outdoor Jacket",
    category: "Jackets",
    price: 1160,
    sizes: ["M", "L"],
    color: "Beige",
    inStock: true,
    rating: 4.1,
    image: "https://placehold.co/400x500/d8c9a8/000?text=Beige+Windbreaker",
  },
  {
    id: 58,
    name: "Red Warm Puffer Coat",
    category: "Jackets",
    price: 1160,
    sizes: ["M", "L", "XL"],
    color: "Red",
    inStock: true,
    rating: 3.9,
    image: "https://placehold.co/400x500/b22222/fff?text=Red+Puffer+Jacket",
  },
  {
    id: 59,
    name: "Black Quilted Puffer",
    category: "Jackets",
    price: 1180,
    sizes: ["M", "L"],
    color: "Black",
    inStock: true,
    rating: 5.0,
    image: "https://placehold.co/400x500/111/fff?text=Black+Puffer+Jacket",
  },
  {
    id: 60,
    name: "White Quilted Puffer",
    category: "Jackets",
    price: 1200,
    sizes: ["M", "L", "XL"],
    color: "White",
    inStock: true,
    rating: 4.8,
    image: "https://placehold.co/400x500/eee/000?text=White+Puffer+Jacket",
  },

  /***************** Shorts *************************** */
  {
    id: 61,
    name: "Olive Running Shorts",
    category: "Shorts",
    price: 220,
    sizes: ["S", "M", "L"],
    color: "Olive Green",
    inStock: true,
    rating: 4.6,
    image:
      "https://placehold.co/400x500/556b2f/fff?text=Olive+Green+Sport+Shorts",
  },
  {
    id: 62,
    name: "Blue Training Shorts",
    category: "Shorts",
    price: 240,
    sizes: ["S", "M", "L", "XL"],
    color: "Blue",
    inStock: true,
    rating: 4.4,
    image: "https://placehold.co/400x500/2a4d8f/fff?text=Blue+Sport+Shorts",
  },
  {
    id: 63,
    name: "Beige Running Shorts",
    category: "Shorts",
    price: 260,
    sizes: ["S", "M", "L"],
    color: "Beige",
    inStock: false,
    rating: 4.2,
    image: "https://placehold.co/400x500/d8c9a8/000?text=Beige+Sport+Shorts",
  },
  {
    id: 64,
    name: "Red Cargo Fit Shorts",
    category: "Shorts",
    price: 260,
    sizes: ["S", "M", "L", "XL"],
    color: "Red",
    inStock: true,
    rating: 4.0,
    image: "https://placehold.co/400x500/b22222/fff?text=Red+Cargo+Shorts",
  },
  {
    id: 65,
    name: "Black Cargo Bermudas",
    category: "Shorts",
    price: 280,
    sizes: ["S", "M", "L"],
    color: "Black",
    inStock: true,
    rating: 3.8,
    image: "https://placehold.co/400x500/111/fff?text=Black+Cargo+Shorts",
  },
  {
    id: 66,
    name: "White Cargo Bermudas",
    category: "Shorts",
    price: 300,
    sizes: ["S", "M", "L", "XL"],
    color: "White",
    inStock: true,
    rating: 4.9,
    image: "https://placehold.co/400x500/eee/000?text=White+Cargo+Shorts",
  },
  {
    id: 67,
    name: "Gray Jean Shorts Fit",
    category: "Shorts",
    price: 300,
    sizes: ["S", "M", "L"],
    color: "Gray",
    inStock: true,
    rating: 4.7,
    image: "https://placehold.co/400x500/888/fff?text=Gray+Denim+Shorts",
  },
  {
    id: 68,
    name: "Navy Jean Shorts Fit",
    category: "Shorts",
    price: 320,
    sizes: ["S", "M", "L", "XL"],
    color: "Navy",
    inStock: true,
    rating: 4.5,
    image: "https://placehold.co/400x500/1f2a44/fff?text=Navy+Denim+Shorts",
  },
  {
    id: 69,
    name: "Olive Denim Bermudas",
    category: "Shorts",
    price: 340,
    sizes: ["S", "M", "L"],
    color: "Olive Green",
    inStock: true,
    rating: 4.3,
    image:
      "https://placehold.co/400x500/556b2f/fff?text=Olive+Green+Denim+Shorts",
  },
  {
    id: 70,
    name: "Blue Game Day Shorts",
    category: "Shorts",
    price: 340,
    sizes: ["S", "M", "L", "XL"],
    color: "Blue",
    inStock: false,
    rating: 4.1,
    image:
      "https://placehold.co/400x500/2a4d8f/fff?text=Blue+Basketball+Shorts",
  },
  {
    id: 71,
    name: "Beige Court Bermudas",
    category: "Shorts",
    price: 360,
    sizes: ["S", "M", "L"],
    color: "Beige",
    inStock: true,
    rating: 3.9,
    image:
      "https://placehold.co/400x500/d8c9a8/000?text=Beige+Basketball+Shorts",
  },
  {
    id: 72,
    name: "Red Mesh Hoop Shorts",
    category: "Shorts",
    price: 380,
    sizes: ["S", "M", "L", "XL"],
    color: "Red",
    inStock: true,
    rating: 5.0,
    image: "https://placehold.co/400x500/b22222/fff?text=Red+Basketball+Shorts",
  },
  {
    id: 73,
    name: "Black Beach Bermudas",
    category: "Shorts",
    price: 380,
    sizes: ["S", "M", "L"],
    color: "Black",
    inStock: true,
    rating: 4.8,
    image: "https://placehold.co/400x500/111/fff?text=Black+Swim+Shorts",
  },
  {
    id: 74,
    name: "White Beach Bermudas",
    category: "Shorts",
    price: 400,
    sizes: ["S", "M", "L", "XL"],
    color: "White",
    inStock: true,
    rating: 4.6,
    image: "https://placehold.co/400x500/eee/000?text=White+Swim+Shorts",
  },
  {
    id: 75,
    name: "Gray Swimming Shorts",
    category: "Shorts",
    price: 420,
    sizes: ["S", "M", "L"],
    color: "Gray",
    inStock: true,
    rating: 4.4,
    image: "https://placehold.co/400x500/888/fff?text=Gray+Swim+Shorts",
  },

  /***************** Shoes *************************** */
  {
    id: 76,
    name: "Blue Casual Sneakers",
    category: "Shoes",
    price: 1200,
    sizes: ["40", "41", "42", "43", "44"],
    color: "Blue",
    inStock: true,
    rating: 4.2,
    image: "https://placehold.co/400x500/2a4d8f/fff?text=Blue+Casual+Sneakers",
  },
  {
    id: 77,
    name: "Beige Daily Sneakers",
    category: "Shoes",
    price: 1220,
    sizes: ["40", "41", "42", "43"],
    color: "Beige",
    inStock: false,
    rating: 4.0,
    image: "https://placehold.co/400x500/d8c9a8/000?text=Beige+Casual+Sneakers",
  },
  {
    id: 78,
    name: "Red Classic Sneakers",
    category: "Shoes",
    price: 1240,
    sizes: ["40", "41", "42", "43", "44"],
    color: "Red",
    inStock: true,
    rating: 3.8,
    image: "https://placehold.co/400x500/b22222/fff?text=Red+Casual+Sneakers",
  },
  {
    id: 79,
    name: "Black High-Top Shoes",
    category: "Shoes",
    price: 1240,
    sizes: ["40", "41", "42", "43"],
    color: "Black",
    inStock: true,
    rating: 4.9,
    image: "https://placehold.co/400x500/111/fff?text=Black+High-Top+Sneakers",
  },
  {
    id: 80,
    name: "White High-Top Shoes",
    category: "Shoes",
    price: 1260,
    sizes: ["40", "41", "42", "43", "44"],
    color: "White",
    inStock: true,
    rating: 4.7,
    image: "https://placehold.co/400x500/eee/000?text=White+High-Top+Sneakers",
  },
  {
    id: 81,
    name: "Gray Hi-Top Sneakers",
    category: "Shoes",
    price: 1280,
    sizes: ["40", "41", "42", "43"],
    color: "Gray",
    inStock: true,
    rating: 4.5,
    image: "https://placehold.co/400x500/888/fff?text=Gray+High-Top+Sneakers",
  },
  {
    id: 82,
    name: "Navy Chunky Sneakers",
    category: "Shoes",
    price: 1280,
    sizes: ["40", "41", "42", "43", "44"],
    color: "Navy",
    inStock: true,
    rating: 4.3,
    image: "https://placehold.co/400x500/1f2a44/fff?text=Navy+Chunky+Sneakers",
  },
  {
    id: 83,
    name: "Olive Platform Shoes",
    category: "Shoes",
    price: 1300,
    sizes: ["40", "41", "42", "43"],
    color: "Olive Green",
    inStock: true,
    rating: 4.1,
    image:
      "https://placehold.co/400x500/556b2f/fff?text=Olive+Green+Chunky+Sneakers",
  },
  {
    id: 84,
    name: "Blue Chunky Sneakers",
    category: "Shoes",
    price: 1320,
    sizes: ["40", "41", "42", "43", "44"],
    color: "Blue",
    inStock: false,
    rating: 3.9,
    image: "https://placehold.co/400x500/2a4d8f/fff?text=Blue+Chunky+Sneakers",
  },
  {
    id: 85,
    name: "Beige Slip-On Loafer",
    category: "Shoes",
    price: 1320,
    sizes: ["40", "41", "42", "43"],
    color: "Beige",
    inStock: true,
    rating: 5.0,
    image: "https://placehold.co/400x500/d8c9a8/000?text=Beige+Slip-Ons",
  },
  {
    id: 86,
    name: "Red Slip-On Sneakers",
    category: "Shoes",
    price: 1340,
    sizes: ["40", "41", "42", "43", "44"],
    color: "Red",
    inStock: true,
    rating: 4.8,
    image: "https://placehold.co/400x500/b22222/fff?text=Red+Slip-Ons",
  },
  {
    id: 87,
    name: "Black Slip-On Loafer",
    category: "Shoes",
    price: 1360,
    sizes: ["40", "41", "42", "43"],
    color: "Black",
    inStock: true,
    rating: 4.6,
    image: "https://placehold.co/400x500/111/fff?text=Black+Slip-Ons",
  },
  {
    id: 88,
    name: "White Sport Sneakers",
    category: "Shoes",
    price: 1360,
    sizes: ["40", "41", "42", "43", "44"],
    color: "White",
    inStock: true,
    rating: 4.4,
    image: "https://placehold.co/400x500/eee/000?text=White+Running+Shoes",
  },
  {
    id: 89,
    name: "Gray Runner Sneakers",
    category: "Shoes",
    price: 1380,
    sizes: ["40", "41", "42", "43"],
    color: "Gray",
    inStock: true,
    rating: 4.2,
    image: "https://placehold.co/400x500/888/fff?text=Gray+Running+Shoes",
  },
  {
    id: 90,
    name: "Navy Runner Sneakers",
    category: "Shoes",
    price: 1400,
    sizes: ["40", "41", "42", "43", "44"],
    color: "Navy",
    inStock: true,
    rating: 4.0,
    image: "https://placehold.co/400x500/1f2a44/fff?text=Navy+Running+Shoes",
  },
];

